name: eden
description: A new Flutter project.

publish_to: "none"

version: 1.7.7+47

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  passwordfield: ^0.1.0
  intl_phone_number_input: ^0.7.0+2
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  shared_preferences:
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  image_gallery_saver: ^1.7.1
  change_app_package_name: ^1.0.0
  http: ^0.13.4
  radio_player: ^0.5.1
  url_launcher: ^6.0.20
  flutter_share: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  fijkplayer: ^0.10.1
  sliding_up_panel: ^2.0.0+1
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  responsive_framework: ^0.2.0
  flutter_facebook_auth: ^4.3.4+2
  app_tracking_transparency: ^2.0.2+4
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.4
  firebase_database: ^9.0.9
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/images/1logo.png"
  android: "ic_laucher" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/logo_bg.png" # only available for Android 8.0 devices and above

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
